### PR TITLE
Added map functionality and additional attributes

### PR DESCRIPTION
**Pull request by torstenknoefel**
I have married up your repo (V 5.5.0) with the code from this repo: https://github.com/SmarthomeAddicted/Indego-Integration.
(I used diff to add the missing code and adapted slightly.)

This relates to my feature request #212

### CODE REVIEW

**Comment by sander1988** [comment]
Just noticed something... I don't think it will work correctly with multiple mowers. The SVG uses a static file/path. So the SVG will be overwritten with multiple mowers.

**Comment by mateusz-lichota** [comment]
Hi! I'm interested in working on this PR. What needs to be done before merging? @jm-73

**Comment by sander1988** [comment]
Hi @mateusz-lichota! We have not received any replies to my questions in this PR. 

**To summarize what's discussed:**
- My questions regarding impact on number of API requests.
- Make this feature optional through config ; disabled by default.
- Check the possible SVG issue with multiple mower. I have not tested, but I suspect a bug based on looking at the code.

I just released version 5.7.0 ; so also sync with latest version on develop branch.

Just let me know when all is implemented/fixed so I (and maybe others) can test it.

**Comment by mateusz-lichota** [comment]
Regarding your concerns:

- The number of API calls: Currently 4 requests to the API are made every 10 minutes. This PR increases that to 5, which I don't think could result in being blocked
- Making the feature optional: Downloading the map is exposed as a HA service that has to be executed manually by the user. I'll change the code in a way which only performs any tasks related to position updates if the map has been downloaded.
- Multiple mowers: The service for downloading the map allows you to choose any name for the file, but the code that performs position updates will only work if you use the default filename, and as you said, will fail if there are multiple mowers. I'm in favor of removing the ability to choose a custom filename (since it adds no real value), and instead add the unique mower id to the filename.

I'll copy the map-related changes (discarding the alert-related stuff, which should arguably be a separate PR) from @torstenknoefel 's branch into my fork and make those changes, then open a new PR

**Pull request closed without merging**
