### PR TITLE
Added mower state and mower state detail translations

### PR DESCRIPTION
**Pull request by kimzeuner**
I have added the translations for the entities "mower state" and "mower state detail" (#228).
The translations are missing in the en.json as the states are already in english.
The translation files for fr, nl, and pl have to be changed, i have already added the lines so only the german text has to be changed.
@zmechu @urbatecte is it possible that you translate the new lines once again ? 
@sander1988 not sure but have you done the nl translations in the past ?

### CODE REVIEW

**Comment by sander1988** [comment]
@kimzeuner ...

> @zmechu @urbatecte is it possible that you translate the new lines once again ?

Is this done / ok. Can we merge?

> @sander1988 not sure but have you done the nl translations in the past ?

That's fine. I will do this after merge on the develop branch.

**Comment by kimzeuner** [comment]
I don't think so as i have not heard anything since i opened the PR 😏

**Comment by sander1988** [comment]
> I don't think so as i have not heard anything since i opened the PR 😏

Ok.

---

@translators ... 

I have just updated the text of [translation connection_error](https://github.com/sander1988/Indego/commit/c20fc84ccd7b667ebd672f0f795b300e6f0ca3e9#diff-27c675a717e3f010cb948a4d67f4a6b9ac1497ad97f19ab9ec51fae0b0c2cf94R5) ; please also update that one your native language. I have done the EN and NL texts.

Please sync with the develop branch before committing the new translations to prevent merge errors.

**Comment by urbatecte** [comment]
Hi @sander1988 !
Please find here attached the fr.json translation file.
[fr.json](https://github.com/user-attachments/files/16324546/fr.json)

I think some messages may be still missing.
"Stop button have been pushed"
kind of warning message regarding the "blades wear" associated with hours count
kind of "lawn have not been lawed since long time, so it will be done two time"

Thanks for your work @sander1988 
Cheers

**Comment by kimzeuner** [comment]
All possible updates were merged for the PR. I have also included the sk.json from PR #244 

@urbatecte Thanks for your work too, As sander1988 just updated the translation for config -> abort -> connection_error could you maybe have a look at this and update the second sentence ? 
Regarding the missing messages, i think the messages that you mentioned are alerts, arent they ? Alerts schould be shown in the native language anyway so there is no need to translate them. But let me know when i`m wrong and i will take care of it.

**Comment by urbatecte** [comment]
@kimzeuner please find me updated file
[fr.json](https://github.com/user-attachments/files/16432822/fr.json)

Cheers

**Comment by kimzeuner** [comment]
Thanks a lot, i have added your translations ;)
@sander1988 I think i have merged all available translations.

**Pull request merged**
